### ISSUE TITLE
Status dos Pagamento = Incompleto

### ISSUE THREAD

**Issue by andremayer** [antonioantunes/whmcs-pagseguro-api-lite#1]
Pode me ajudar?

![pagseguro api lite](https://cloud.githubusercontent.com/assets/1262917/9075452/507237e4-3aeb-11e5-80c2-cf7144de4ea9.jpg)

Configurei de acordo com teu github, mas não funcionou :(

**Comment by antonioantunes** [comment]
Olá!

Favor verificar no menu "Billing", "Gateway Log", se é apresentada algum retorno de transação.

Você está utilizando o commit mais recente, do dia 16/07?

**Comment by antonioantunes** [comment]
Olá!

Verifiquei que a partir do WHMCS v6.0, o arquivo dbconnect.php foi substituído pelo init.php.

Já fiz um novo commit para corrigir a falha, peço que efetue um teste e informe caso o problema persista.

Obrigado por reportar este problema!

**Comment by andremayer** [comment]
Olá
Eu que lhe agradeço!
Testei no meu WHMCS v6.0 e agora funcionou corretamente! Muito obrigado!
Um Abraço!
Andre Mayer

Date: Sun, 16 Aug 2015 11:38:04 -0700
