### ISSUE TITLE
Ajuda

### ISSUE THREAD

**Issue by vagner-baggio** [antonioantunes/whmcs-pagseguro-api-lite#2]
Olá, Antonio! Tudo bem?

Amigo, me tira uma dúvida por favor. Pelo que pude ver o WHMCS tem um módulo do pagseguro nativo é isso mesmo? Ou é só o módulo de integração e para fazer os retornos precisaria usar este seu módulo?

Obrigado e grande abraço.

**Comment by antonioantunes** [comment]
Olá!

O WHMCS possui módulo nativo sim, e este módulo nativo possui também retorno, mas pelo menos na data que elaborei este novo, o nativo não utilizava a API de Pagamentos, e sim algumas tecnologias antigas que o PagSeguro desaconselha o uso:
Encaminhamento dos dados para o PagSeguro através de formulário HTML simples: https://pagseguro.uol.com.br/v2/guia-de-integracao/pagamento-via-html.html
Retorno dos dados via retorno automático de dados: https://pagseguro.uol.com.br/desenvolvedor/retorno_automatico_de_dados.jhtml

Vendo a documentação do WHMCS sobre o módulo (http://docs.whmcs.com/PagSeguro) eu acredito que o mesmo não tenha sido atualizado desde então, visto que ainda é necessária a configuração manual da URL de Retorno.

Podemos citar como desvantagens da utilização do encaminhamento dos dados via formulário HTML 
1. O mesmo ter sido noticiado pelo próprio PagSeguro que será descontinuado futuramente. Acessando sua conta, na opção "Preferências, Integrações", há a mensagem: "Habilitar pagamentos via Formulário HTML
Esse tipo de integração não terá atualizações e será descontinuada. 
No entanto, você ainda pode habilitar essa opção." 
2. A possibilidade de modificação dos dados por um cliente mal intencionado, que pode vir a alterar dados da transação a fim de fazer parecê-la válida, com outras informações. Utilizando a API, tais dados trafegam diretamente do seu WHMCS para o PagSeguro, sendo impossível ao cliente modificá-los no meio do caminho, aumentando assim a segurança.

Já quanto ao retorno automático da transação, os problemas são os seguintes:
1. O mesmo foi descontinuado para novas implementações. Acessando a mesma página do item anterior, temos: "Atenção!
O retorno automático de dados foi descontinuado para novas implementações. Confira informações dessa funcionalidade."
2. O principal problema é que a URL de retorno precisa ser configurada manualmente na sua conta, via Painel do PagSeguro, e a mesma é fixa, e somente uma por conta. Desta forma, se você utiliza a mesma conta PagSeguro para mais de uma empresa ou site, o retorno apenas funcionará em uma delas, a menos que você implemente algo que faça o redirecionamento para o local correto. Utilizando a API de Pagamentos, a URL de retorno é passada em cada transação, então você pode utilizar a mesma conta em mais de um local sem problema algum.

Além destas duas questões, o módulo nativo encontra-se protegido por ioncube (tecnologia utilizada no WHMCS para proteger o código fonte), o que impossibilita (ou pelo menos dificulta) a verificação da segurança do código e também impossibilita alterações (customizações ou novas funções).

Se tiver qualquer outra dúvida, pode me perguntar.

Um grande abraço!
